# -*- coding: utf-8 -*-
"""radedit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7yDRr3Qahl3RjHS67Q1iiPw-dBwdp9N
"""

!pip install -U diffusers

"""## Local Inference on GPU
Model page: https://huggingface.co/microsoft/radedit

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/microsoft/radedit)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏

The model you are trying to use is gated. Please make sure you have access to it by visiting the model page.To run inference, either set HF_TOKEN in your environment variables/ Secrets or run the following cell to login. 🤗
"""

!hf auth login

!pip install diffusers transformers torch torchvision huggingface-hub accelerate Pillow

from transformers import AutoModel, AutoTokenizer
from diffusers import AutoencoderKL, DDIMScheduler, StableDiffusionPipeline, UNet2DConditionModel

unet_loaded = UNet2DConditionModel.from_pretrained("microsoft/radedit", subfolder="unet")
vae = AutoencoderKL.from_pretrained("stabilityai/sdxl-vae")
text_encoder = AutoModel.from_pretrained("microsoft/BiomedVLP-BioViL-T", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("microsoft/BiomedVLP-BioViL-T", model_max_length=128, trust_remote_code=True)
scheduler = DDIMScheduler(
    beta_schedule="linear",
    clip_sample=False,
    prediction_type="epsilon",
    timestep_spacing="trailing",
    steps_offset=1,
)

generation_pipeline = StableDiffusionPipeline(
    vae=vae,
    text_encoder=text_encoder,
    tokenizer=tokenizer,
    unet=unet_loaded,
    scheduler=scheduler,
    safety_checker=None,
    requires_safety_checker=False,
    feature_extractor=None,
)
generation_pipeline.to("cuda")



import torch

prompts = ["Pnuemocystis pneumonia"]

torch.manual_seed(0)
images = generation_pipeline(
    prompts,
    num_inference_steps=100,
    guidance_scale=7.5,
).images

images[0].save("test_output.png")
images[0]  # displays inline in Colab